name: Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for the docker image'
        required: true
        type: string
        default: 'stable'
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run:  docker build . --tag ghcr.io/fractal-analytics-platform/fractal-vizarr-viewer:${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'dev' }}

      - name: Push the Docker Image
        run: docker push ghcr.io/fractal-analytics-platform/fractal-vizarr-viewer:${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'dev' }}
