name: Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag for the docker image"
        required: true
        type: string
        default: "stable"
  push:
    branches: ["main"]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
        env:
          GITHUB_ACTOR: ${{ github.actor }}

      - run: docker build . --tag "ghcr.io/fractal-analytics-platform/fractal-data:${VERSION}"
        env:
          VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'dev' }}

      - run: docker push "ghcr.io/fractal-analytics-platform/fractal-data:${VERSION}"
        env:
          VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'dev' }}
