name: Unit tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  unit_tests:
    name: 'Node ${{ matrix.node-version }}'
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: ['18', '20']

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run unit tests
        run: npm run test
