name: Unit tests

on:
  push:
    branches: ["main", "ihb-develop"]
  pull_request:
    branches: ["main", "ihb-develop"]

permissions: {}

jobs:
  unit_tests:
    name: "Node ${{ matrix.node-version }}"
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: ["24"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm run install:aws
      - run: npm run build
      - run: npm run test
